# Generated by Django 5.0 on 2023-12-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alert_alertthreshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='vehicle_no',
        ),
    ]
